In [ ]:
ic = 0
sl = 1
lr = 0.01
step = range(100)
for ind, step  in enumerate(step):
    d_dint = -2*(1.4-(ic+sl*0.5))-2*(3.2-(ic+sl*2.9))-2*(1.9-(ic+sl*2.3))
    d_dslope = - 2*0.5*(1.4-(ic+sl*0.5))-2*2.9*(3.2-(ic+sl*2.9))-2*2.3*(1.9-(ic+sl*2.3))
    s_size_i = lr*d_dint 
    new_ic = ic-s_size_i
    ic = new_ic
    s_size_s = lr*d_dslope 
    new_sl = sl-s_size_s
    sl = new_sl
    print("The di4fferential intercept and slope at step {}: \n{}\n{}".format(ind+1, d_dint, d_dslope))
print(ic, sl)


In [32]:
2.3 - (0.653+0.767*1.9)

0.18969999999999976

In [25]:
import numpy as np
print("training process started...")
T= 0.05
ln= 0.4
x1= 0.1
w1= 0.15
b1= 0.40
w2= 0.45
b2= 0.65
z1 = x1*w1+b1
a1 = 1/(1+np.exp(-z1))
z2 = a1*w2+b2
a2 = 1/(1+np.exp(-z2))
E = 0.5*(T-a2)**2
print(a2)
while np.abs(E) >0.000001:
    dE_dw2 = (a2-T)*(a2*(1-a2))*(a1)
    dE_db2 = (a2-T)*(a2*(1-a2))*1
    dE_dw1 = (a2-T)*(a2*(1-a2))*(w2)*(a1*(1-a1))*(x1)
    dE_db1 = (a2-T)*(a2*(1-a2))*(w2)*(a1*(1-a1))*1
    w2 -= (ln*dE_dw2)
    b2 -= (ln*dE_db2)
    w1 -= (ln*dE_dw1)
    b1 -= (ln*dE_db1)
    z1 = x1*w1+b1
    a1 = 1/(1+np.exp(-z1))
    z2 = a1*w2+b2
    a2 = 1/(1+np.exp(-z2))
    E = 0.5*(T-a2)**2
print(a2,E)

training process started...
0.7152516802527555
0.0514122470448081 9.97220857784606e-07


In [25]:
import numpy as np
x1, x2, T, lnt= .5, .4, .78, 0.00045
w111, w112, w113, w121, w122, w123, b11, b12, b13, w211, w221, w231, b2 = np.round(np.random.rand(13), decimals=3)
print("Started the training process from here... ")
print(w111, w112, w113, w121, w122, w123, b11, b12, b13, w211, w221, w231, b2)
z11 = w111*x1 + w121*x2 + b11
z12 = w112*x1 + w122*x2 + b12
z13 = w113*x1 + w123*x2 + b13
a11 = 1/(1+np.exp(-z11))
a12 = 1/(1+np.exp(-z12))
a13 = 1/(1+np.exp(-z13))
z2 = w211*a11 + w221*a12 + w231*a13 + b2
a2 = 1/(1+np.exp(-z2))
E = 0.5*(T-a2)**2
while np.abs(E) > 0.00000001:
    dE_dw111 = (a2-T)*(a2*(1-a2))*(w211)*(a11*(1-a11))*x1
    dE_dw121 = (a2-T)*(a2*(1-a2))*(w211)*(a11*(1-a11))*x2
    dE_db11 = (a2-T)*(a2*(1-a2))*(w211)*(a11*(1-a11))*1
    dE_dw112 = (a2-T)*(a2*(1-a2))*(w221)*(a12*(1-a12))*x1
    dE_dw122 = (a2-T)*(a2*(1-a2))*(w221)*(a12*(1-a12))*x2
    dE_db12 = (a2-T)*(a2*(1-a2))*(w221)*(a12*(1-a12))*1
    dE_dw113 = (a2-T)*(a2*(1-a2))*(w231)*(a13*(1-a13))*x1
    dE_dw123 = (a2-T)*(a2*(1-a2))*(w231)*(a13*(1-a13))*x2
    dE_db13 = (a2-T)*(a2*(1-a2))*(w231)*(a13*(1-a13))*1
    dE_dw211 = (a2-T)*(a2*(1-a2))*a11
    dE_dw221 = (a2-T)*(a2*(1-a2))*a12
    dE_dw231 = (a2-T)*(a2*(1-a2))*a13
    dE_db2 = (a2-T)*(a2*(1-a2))*1

    w111 -= (lnt*dE_dw111)
    w121 -= (lnt*dE_dw121)
    b11 -= (lnt*dE_db11)
    w112 -= (lnt*dE_dw112)
    w122 -= (lnt*dE_dw122)
    b12 -= (lnt*dE_db12)
    w113 -= (lnt*dE_dw113)
    w123 -= (lnt*dE_dw123)
    b13 -= (lnt*dE_db13)
    w211 -= (lnt*dE_dw211)
    w221 -= (lnt*dE_dw221)
    w231 -= (lnt*dE_dw231)
    b2 -= (lnt*dE_db2)
    
    z11 = w111*x1 + w121*x2 + b11
    z12 = w112*x1 + w122*x2 + b12
    z13 = w113*x1 + w123*x2 + b13
    a11 = 1/(1+np.exp(-z11))
    a12 = 1/(1+np.exp(-z12))
    a13 = 1/(1+np.exp(-z13))
    z2 = w211*a11 + w221*a12 + w231*a13 + b2
    a2 = 1/(1+np.exp(-z2))
    E = 0.5*(T-a2)**2
print("break")
print(w111, w112, w113, w121, w122, w123, b11, b12, b13, w211, w221, w231, b2)
print("Result and Cost Function: ")
print(a2, E)

Started the training process from here... 
0.027 0.846 0.131 0.91 0.953 0.267 0.491 0.61 0.807 0.63 0.663 0.35 0.234
break
0.0223673018869212 0.842327839630082 0.1286393000129173 0.9062938415095312 0.9500622717040723 0.26511144001033143 0.4817346037738373 0.6026556792601842 0.8022786000258045 0.5783523424603288 0.6039659898919212 0.29664528661567996 0.1605380139988815
Result and Cost Function: 
0.780141421103897 9.999964313711937e-09


In [84]:
class Network(object):
    def __init__(self, *layers):
        self.layers = layers
        self.num_layers = len(layers)
        self.weights = [np.random.rand(n,m) for m, n in zip(layers[:-1], layers[1:])] 
        self.biases = [np.random.rand(n,1) for n in layers[1:]]

    def sigmoid_activation(self,a):
        if self.num_layers >= 4:
            for w, b in zip(self.weights[:-2], self.biases[:-2]):
                a = sigmoid(np.dot(w,a)+b)
            return a
        else:
            for w, b in zip(self.weights, self.biases):
                a = sigmoid(np.dot(w,a)+b)
            return a
                
    def tanh_activation(self,a):
        if self.num_layers >= 4:
            for w, b in zip(self.weights[-2:], self.biases[-2:]):
                a = tanh(np.dot(w,a)+b)
            return a
        else:
            return a
    
    def SDG(self, data, batch_size, eta, epochs):
        break
    
def sigmoid(z):
    a = 1/(1+np.exp(-z))
    return a

def sigmoid_derivative(z):
    a = sigmoid(z)*(1-sigmoid(z))
    return a

def tanh(z):
    a = np.tanh(z)
    return a

def tanh_derivative(z):
    a = 1 - tanh(z)**2
    return a

def relu(z):
    a = np.maximum(0,z)
    return a

def relu_derivative(z):
    a = np.where(relu(z) > 0, 1, 0)
    return a
    
net = Network(2, 4, 1, 2)
# print(net.weights)
# print()
# print(net.biases)

net.move(np.array([[1],[2]]))

[[0.82082778]
 [0.73766881]
 [0.91544832]
 [0.88678466]]

[[0.91625243]]

[[0.39372189]
 [0.36216472]]



array([[0.39372189],
       [0.36216472]])

In [76]:
lis = [1, 2, 3]
def display(a):
    for i in a:
        i += i
    return i

display(lis)

6

In [ ]:
import pandas as pd
pd.