In [ ]:
!py -m pip install --upgrade pip

In [7]:
import numpy as np

weights = np.around(np.random.uniform(size=6), decimals=2)
biases = np.around(np.random.uniform(size=3), decimals=2)

In [8]:
print(weights)
print(biases)

[0.86 0.44 0.27 0.84 0.72 0.49]
[0.01 0.98 0.55]


In [10]:
x_1 = 0.1
x_2 = 0.15

print('The inputs are {} and {}'.format(x_1, x_2))

The inputs are 0.1 and 0.15


In [12]:
z_11 = x_1*weights[0] + x_2*weights[1] + biases[0]
z_12 = x_1*weights[2] + x_2*weights[3] + biases[1]

print('The weighted sum the inputs at the first node is {}'.format(z_11))
print('The weighted sum the inputs at the second node is {}'.format(z_12))

The weighted sum the inputs at the first node is 0.16200000000000003
The weighted sum the inputs at the second node is 1.133


In [14]:
a_11 = 1.0 / (1.0 + np.exp(-z_11))
a_12 = 1.0 / (1.0 + np.exp(-z_12))

print('The activation of the first node is {}'.format(np.around(a_11, decimals=4)))
print('The activation of the second node is {}'.format(np.around(a_12, decimals=4)))

The activation of the first node is 0.5404
The activation of the second node is 0.7564


In [16]:
z_2 = a_11*weights[4] + a_12*weights[5] + biases[2]

print('The weighted sum of all nodes at the output layer is {}'.format(np.around(z_2, decimals=4)))

The weighted sum of all nodes at the output layer is 1.3097


In [18]:
a_2 = 1.0 / (1.0 + np.exp(-z_2))
a_2

np.float64(0.7874677255096606)

In [22]:
n = 3
num_hidden_layers = 4
m = [2, 3, 1, 5]
num_output_nodes = 2

In [23]:
import numpy as np

num_nodes_prev = n

network = {}

for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_output_nodes
    else :
        layer_name = 'h_layer_{}'.format(layer+1)
        num_nodes = m[layer]

    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
        'weights': np.around(np.random.uniform(size=num_nodes_prev), decimals=2),
        'biases': np.around(np.random.uniform(size=1), decimals=2)
        }
    num_nodes_prev = num_nodes

print(network)

{'h_layer_1': {'node_1': {'weights': array([0.31, 0.98, 0.04]), 'biases': array([0.19])}, 'node_2': {'weights': array([0.4 , 0.64, 0.93]), 'biases': array([0.6])}}, 'h_layer_2': {'node_1': {'weights': array([0.5 , 0.61]), 'biases': array([0.77])}, 'node_2': {'weights': array([0.72, 0.86]), 'biases': array([0.45])}, 'node_3': {'weights': array([0.62, 0.51]), 'biases': array([0.51])}}, 'h_layer_3': {'node_1': {'weights': array([0.27, 0.4 , 0.74]), 'biases': array([0.9])}}, 'h_layer_4': {'node_1': {'weights': array([0.36]), 'biases': array([0.1])}, 'node_2': {'weights': array([0.32]), 'biases': array([0.56])}, 'node_3': {'weights': array([0.12]), 'biases': array([0.41])}, 'node_4': {'weights': array([0.08]), 'biases': array([0.25])}, 'node_5': {'weights': array([1.]), 'biases': array([0.15])}}, 'output': {'node_1': {'weights': array([0.04, 0.79, 0.55, 0.24, 0.09]), 'biases': array([0.2])}, 'node_2': {'weights': array([0.68, 0.08, 0.35, 0.38, 0.76]), 'biases': array([0.1])}}}


In [50]:
def initialize_network (num_inputs, num_hidden_layers, num_hidden_nodes, num_output_nodes):
    num_prev_node = num_inputs
    network = {}
    for layer in range(num_hidden_layers+1):
        if layer == num_hidden_layers:
            layer_name = 'output'
            num_node = num_output_nodes
        else :
            layer_name = 'layer_{}'.format(layer+1)
            num_node = num_hidden_nodes[layer]

        network[layer_name] = {}
        for node in range(num_node):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_prev_node), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2)
            }
        num_prev_node = num_node

    return network

In [51]:
small_network = initialize_network(2, 4, [2, 5, 3, 7], 3)

In [52]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [53]:
from random import seed
import numpy as np

np.random.seed(5)
inputs = np.around(np.random.uniform(size=2), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.22 0.87]


In [55]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']

compute_weighted_sum(inputs, node_weights, node_bias)

array([1.0807])

In [56]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [73]:
np.around(node_activation(compute_weighted_sum(inputs, node_weights, node_bias))[0], decimals=4)

np.float64(0.7466)

In [74]:
def forward_propagate(network, inputs):
    layer_inputs = inputs
    for layer in network:
        layer_data = network[layer]

        layer_outputs = []
        for node in layer_data:
            node_data = layer_data[node]

            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            
            layer_outputs.append(float(np.around(node_output[0], decimals=4)))

        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs

    network_predictions = layer_outputs
    return network_predictions

In [75]:
forward_propagate(small_network, inputs)

The outputs of the nodes in hidden layer number 1 is [0.7466, 0.6821]
The outputs of the nodes in hidden layer number 2 is [0.8559, 0.6495, 0.7517, 0.8513, 0.7265]
The outputs of the nodes in hidden layer number 3 is [0.9758, 0.9435, 0.8584]
The outputs of the nodes in hidden layer number 4 is [0.7904, 0.7682, 0.9513, 0.8524, 0.9162, 0.859, 0.8504]


[0.9807, 0.9795, 0.9021]

In [77]:
1.0/(1.0+np.exp(--0.4))

np.float64(0.401312339887548)

In [ ]:
import numpy as np
sec = 6
guess = 0
while guess != sec:
    guess = np.random.randint(0,21)
    print (guess)